### ISSUE TITLE
New tab functions:<< and >>

### ISSUE THREAD

**Issue by jakejcoffin** [felixerdy/touchbar#19]
Hi!
Really amazing!!! Good touch bar!!

I have a question, is it possible add a function like TAB and shift+TAB for move the code to left or to right for best indent?
EX: editor:move-to-left

Thank u so much and happy work!!

**Comment by felixerdy** [comment]
Thank you and sorry for the late response.

You can modify the buttons by yourself in the `Edit Touchbar` window by either using `editor:indent-selected-rows` or `editor:outdent-selected-rows`
