### ISSUE TITLE
help editing touchbar

### ISSUE THREAD

**Issue by Aj4k** [felixerdy/touchbar#25]
can you help me with the configuration. I'm new to this and i would like my touchbar to have a button with the text " { “ as a shortcut. 

how can i do this

**Comment by felixerdy** [comment]
Thanks for this question. Unfortunately, you can only use Atoms Keybindings as commands for the buttons. I didn't find any keybinding that inserts `{` 😕
You can see all available Keybindings at `Settings` -> `Keybindings`
I may implement this feature in the future
