### ISSUE TITLE
color assignment not working

### ISSUE THREAD

**Issue by goi42** [felixerdy/touchbar#27]
I'm not sure the full extent of this issue, but the colors #FF8900 and #D045BF at least appear to have no effect.

{"type":"popover","label":"git","color":"#FF8900","elements":[{"name":"pull","type":"button","label":"⬇️","command":"github:pull"},{"name":"push","type":"button","label":"⬆️","command":"github:push"},{"name":"commit","type":"button","label":"💾","command":"github:commit"},{"name":"tab","type":"button","label":"👀","command":"github:toggle-git-tab"},{"name":"amend","type":"button","label":"🔃","command":"github:amend-last-commit"}]},

{"type":"popover","label":"edit","color":"#D045BF","elements":[{"name":"comment-button","type":"button","label":"//","command":"editor:toggle-line-comments","color":"#00C6FF"},{"name":"beautify-button","type":"button","label":"💅","command":"atom-beautify:beautify-editor","color":"#A928C8"},{"name":"align","type":"button","label":"👉👈","command":"aligner:align","color":"#0433FF"}]},

**Comment by felixerdy** [comment]
I'm currently not able to check that by myself, but it seems like `TouchBar Popover` has no option to set the backgroundColor. See https://github.com/electron/electron/blob/master/docs/api/touch-bar-popover.md
