### ISSUE TITLE
Iconfont Support

### ISSUE THREAD

**Issue by Teddy95** [felixerdy/touchbar#34]
Hey, I love your plugin :D 
It would be really nice, when you integrate Octicon / FontAwesome icon support.

**Comment by felixerdy** [comment]
Octicon / FontAwesome will not be available in the next time. Currently, e.g. a [TouchBar Button](https://github.com/electron/electron/blob/master/docs/api/touch-bar-button.md) only supports strings (emojis are working) or a [nativeImage](https://github.com/electron/electron/blob/master/docs/api/native-image.md)(which can only use `PNG` or `JPEG`) as its content. 

Inserting emojis into the text field is currently awkward. I'd suggest to copy your desired emoji from somewhere (e.g. https://emojipedia.org/) and paste it into the text field.

You can also insert `PNG` or `JPEG` icons as an absolute path. See #30

**Comment by Teddy95** [comment]
Thank you. I've found a useful website to convert Octicons into images, if anyone has a similar issue: <http://fa2png.io/r/octicons/>

**Comment by danielbayley** [comment]
@felixerdy I don't think this issue should be closed… Also the touchbar-plus package uses Octicons, by first building them (presumable converting their source SVGs to PNGs). This could be a post-install step when this package is installed…
