### ISSUE TITLE
Atom update to 1.47.0 seems to have broken touchbar

### ISSUE THREAD

**Issue by smwoll** [felixerdy/touchbar#49]
Hi and thank you for the awesome package! It has been so helpful. 

I just updated atom to 1.47.0 and haven't been able to get the touch bar working again. I have attempted to restart and uninstall and reinstall the package without any luck. I also attempted to run atom with only the touchbar package enabled. 

I believe this may be related to the update to electron 5.0.13.

Thanks again!

**Comment by grissproject** [comment]
Any news on this issue? I am really missing the touchbar plugin on Atom!

**Comment by AhmedHalat** [comment]
The only touchbar package that seems to be working for me is touchbar-plus by victorhqc. Not sure why all the other packages stopped by hoping for a solution

**Comment by felixerdy** [comment]
I just took a quick look but there are no errors on the console or anything that helps to identify the problem. I will need to investigate further 🕵️‍♂️

**Comment by abhay-agarwal** [comment]
The nightly version of atom last I tested also has touchbar not working (1.48)

**Comment by felixerdy** [comment]
I just did some changes and released version 0.16.0. It's working for me but please test this for me. I'm not able to show the touchbar on startup and now you will need to toggle the touchbar before using it.

On startup, you might be able to see the touchbar for a very short time, I don't know whats happening there.

Still I'm not quite sure what the caused the issue, however the way how I developed the plugin is quite strange and I would do it completely different now.

**Comment by smwoll** [comment]
Thank you so much! After restarting Atom it is working for me. I will test more and let you know if anything changes.

**Comment by AhmedHalat** [comment]
Yeah, thanks!
FYI, I don't seem to get that startup issue you're talking about. 
It starts-up with my atom and doesn't need to be reloaded

**Comment by grissproject** [comment]
Working for me as well! Good job!
