### ISSUE TITLE
Color Picker 

### ISSUE THREAD

**Issue by Austinthemighty** [felixerdy/touchbar#8]
When changing the color via the color slider it will insert the color when you are still choosing

here is a sample of it

`css
#AC2192#A52192#A32192#A02192#9D2192#9B2192#992192#962192#942192#922192#8F2192#8D2192#8A2192#872192#852192#822192#7F2192#792192#752192#712192#6E2192#692192#652192#612192#5D2192#5A2192#552192#512192#4C2192#482192#442192#402192#3B2192#382192#332192#302192#2C2192#2A2192#292192#292192#2A2192#2C2192#302192#352192#3B2192#3F2192#452192#4C2192#542192#5C2192#662192#6D2192#752192#7C2192#842192#8A2192#912192#982192#9F2192#A52192#AB2192#B02192#B52192#BA2192#BE2192#C22192#C62192#C92192#CD2192#D02192#D22192#D42192#D72192#D92192#DC2192#E02192#E32192#E72192#EB2192#EF2192#F32192#F72192#FB2192#FF2192#FF2192#FE2192#F72192#F02192#E82192#E12192#D92192#D22192#CC2192#C52192#BF2192#B92192#B32192#AE2192#A82192#A22192#9B2192#952192#8F2192#8A2192#852192#7F2192#7A2192#752192#702192#6A2192#652192#602192#5B2192#562192#512192#4B2192#452192#402192#392192#332192#2C2192#252192#1F2192#1A2192#152192#102192#0C2192#082192#052192#032192#002192#002192#012192#0C2192#192192#262192#342192#402192#4C2192#592192#672192#752192#822192#8D2192#972192#A02192#A92192#B02192#B72192#BE2192#C42192#C92192#D02192#D52192#DC2192#E22192#E72192#EB2192#EE2192#F12192#F42192#F82192#FB2192#FE2192#FF2192#FA2192#F32192#DE2192#D52192#CD2192#C72192#C02192#B92192#B12192#A82192#9F2192#972192#8D2192#862192#7D2192#752192#6D2192#642192#5D2192#562192#4F2192#482192#432192#3D2192#352192#2E2192#262192#1E2192#162192#0E2192#072192#032192#002192#052192#0E2192#172192#212192#2B2192#342192#3C2192#422192#4A2192#532192#5C2192#662192#702192#792192#822192#8A2192#942192#9D2192#A52192#AC2192#B32192#BA2192#C12192#C82192#CF2192#D42192#D92192#DE2192#E22192#E62192#E82192#EA2192#EA2192#EB2192#EA2192#E82192#E62192#E32192#DE2192#D92192#D22192#CA2192#C32192#BA2192#B12192#A72192#9D2192#932192#882192#7E2192#752192#6B2192#622192#5B2192#532192#4C2192#462192#412192#3D2192#392192
`

this was generated in under 1 second

**Comment by felixerdy** [comment]
Thank you, this should work now

**Comment by felixerdy** [comment]
Still does not work properly
